kind: pipeline
type: exec
name: default

trigger:
    branch:
        - master

platform:
  os: linux
  arch: arm64

steps:
    - name: greeting
      commands:
          - echo "running"
          - echo ${PWD}
          - echo ${DRONE_WORKSPACE}
          - pwd
          - ls -al

    - name: step2
      commands:
          - ls -al

    - name: step3
      commands:
          - ls -al