kind: pipeline
type: docker
name: default

trigger:
    branch:
        - master

steps:
    - name: greeting
      image: hello-world
      commands:
          - echo "running"
          - echo ${PWD}
          - echo ${DRONE_WORKSPACE}

    - name: step2
      commands:
          - echo "running2"
    