kind: pipeline
type: exec
name: default

trigger:
    branch:
        - master

platform:
  os: linux
  arch: arm64

steps:
    - name: greeting
      commands:
          # - which node
          # - which npm
          # - which pnpm
          # - which node123
          - npm i -g pnpm
          - pnpm run build
          # - ls -al ~
          # - echo "running"
          # - echo ${ssh_host}
          # - echo ${ssh_password}
          # - echo ${node123}
          # - pwd
          # - ls -al

    # - name: step2
    #   commands:
    #       - ls -al

    # - name: step3
    #   commands:
    #       - ls -al

    # - name: step4
    #   commands:
    #       - node123       