kind: pipeline
type: docker
name: default

trigger:
    branch:
        - master

platform:
  os: linux
  arch: arm64

steps:
    - name: greeting
      image: node:18.20-alpine
      commands:
          # - which node
          # - which npm
          # - which pnpm
          # - which node123
          # - npm i -g pnpm
          # - pnpm run build
          # - ls -al ~
          # - echo "running"
          # - echo ${ssh_host}
          # - echo ${ssh_password}
          # - echo ${node123}
          - pwd
          - ls -al
          - node -v
          - npm -v
          - node i -g pnpm
          - pnpm i
          - pnpm run build
          - cp -r .otuput /var/www/test_nuxt_proj/

    # - name: deploy
    #   image: nginx:1.21
    #   commands:
    #     - cp -r .otuput /var/www/test_nuxt_proj/
